export const portfolioCards = [
  {
    link: "http://flagman-kirpich.ru/",
    img: "../assets/img/brickproject.png",
    title: "Флагман Кирпич",
    isButton: true,
    description: "",
  },
  {
    link: "http://marianna-cafe.ru/",
    img: "../assets/img/marriana.png",
    title: "Марианна",
    isButton: true,
    description: "",
  },
  {
    link: "https://obektuv.ru/",
    img: "../assets/img/obektuv.png",
    title: "Объектув",
    isButton: true,
    description: "",
  },
  {
    link: "https://mambaroll.ru/",
    img: "../assets/img/mamba.png",
    title: "Черная мамба",
    isButton: true,
    description: "",
  },
  {
    link: "https://github.com/SoloProger/Vue-Shop-Frontend",
    img: "../assets/img/buildingsite.png",
    title: "Сайт строительной компании",
    isButton: true,
    description: "",
  },
  {
    link: "#",
    img: "../assets/img/mysite.png",
    title: "Сайт без фреймворков",
    description: "",
  },
  {
    link: "#",
    img: "../assets/img/personsitev3.png",
    title: "Сайт. Версия 3",
    description: "",
  },
  {
    link: "#",
    img: "../assets/img/personsitev2.png",
    title: "Сайт. Версия 2",
    description: "",
  },
];
